import { beforeEach, describe, expect, it } from 'bun:test'
import { mkdtempSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { defineTsconfig } from '../src/define'
import { nextjs } from '../src/profiles/nextjs'
import { checkAgainstDisk, syncToDisk } from '../src/sync'

let tmp: string

beforeEach(() => {
  tmp = mkdtempSync(join(tmpdir(), 'tsconfig-sync-'))
})

describe('syncToDisk', () => {
  it('writes files initially and marks them unchanged on re-run', async () => {
    const config = defineTsconfig({ profile: nextjs() })
    const first = await syncToDisk(config, tmp)
    expect(first.written).toEqual(['tsconfig.json'])

    const second = await syncToDisk(config, tmp)
    expect(second.written).toEqual([])
    expect(second.unchanged).toEqual(['tsconfig.json'])
  })
})

describe('checkAgainstDisk', () => {
  it('reports missing files', async () => {
    const config = defineTsconfig({ profile: nextjs() })
    const result = await checkAgainstDisk(config, tmp)
    expect(result.ok).toBe(false)
    expect(result.mismatches[0]?.reason).toBe('missing')
  })

  it('passes when disk matches semantically', async () => {
    const config = defineTsconfig({ profile: nextjs() })
    await syncToDisk(config, tmp)
    const result = await checkAgainstDisk(config, tmp)
    expect(result.ok).toBe(true)
  })

  it('ignores formatter-only differences (whitespace, key order)', async () => {
    const config = defineTsconfig({ profile: nextjs() })
    const file = config.files[0]!

    // Write a reformatted version: same content, different indentation, comment injected.
    const reformatted =
      '// AUTO-GENERATED by @infra-x/tsconfig\n' +
      '/* with extra comments */\n' +
      JSON.stringify(file.content, null, 4) +
      '\n'
    writeFileSync(join(tmp, file.filename), reformatted)

    const result = await checkAgainstDisk(config, tmp)
    expect(result.ok).toBe(true)
  })

  it('detects actual value drift (user edited a field)', async () => {
    const config = defineTsconfig({ profile: nextjs() })
    await syncToDisk(config, tmp)

    const file = config.files[0]!
    const tampered = {
      ...file.content,
      compilerOptions: {
        ...file.content.compilerOptions,
        strict: false,
      },
    }
    writeFileSync(join(tmp, file.filename), JSON.stringify(tampered, null, 2))

    const result = await checkAgainstDisk(config, tmp)
    expect(result.ok).toBe(false)
    expect(result.mismatches[0]?.reason).toBe('changed')
  })

  it('tolerates JSONC comments and trailing commas', async () => {
    const config = defineTsconfig({ profile: nextjs() })
    const file = config.files[0]!
    const jsonc = `
// leading comment
{
  "compilerOptions": ${JSON.stringify(file.content.compilerOptions, null, 2)},
  // trailing comma below, tolerated
  "include": ${JSON.stringify(file.content.include)},
  "exclude": ${JSON.stringify(file.content.exclude)},
}
`.trim()
    writeFileSync(join(tmp, file.filename), jsonc)

    const result = await checkAgainstDisk(config, tmp)
    expect(result.ok).toBe(true)
  })
})
