import { buildLayerChain, pickExclude, pickInclude, resolvePrimary } from './layer-chain'
import { mergeCompilerOptions, normalizeCompilerOptions } from './merge'

import type {
  DefineTsconfigInput,
  LayerInput,
  RenderedConfig,
  RenderedFile,
  RenderedTsconfig,
} from './types'

const GENERATED_HEADER = [
  '// AUTO-GENERATED by @infra-x/tsconfig — do not edit directly.',
  '// Edit tsconfig.config.ts and run `tsconfig sync`.',
].join('\n')

export function defineTsconfig(input: DefineTsconfigInput): RenderedConfig {
  const layers = input.layers ?? {}
  const layerNames = Object.keys(layers)

  if (layerNames.length === 0) {
    return { files: [renderSingle(input)] }
  }

  const primaryName = resolvePrimary(input.primary, layerNames)
  const files: RenderedFile[] = []

  for (const name of layerNames) {
    const resolved = resolveLayer(name, input, layers)
    const filename = name === primaryName ? 'tsconfig.json' : `tsconfig.${name}.json`
    files.push({ filename, content: resolved })
  }

  return { files }
}

/** Stringify a rendered file as JSON with the generated header. */
export function renderToString(file: RenderedFile): string {
  return `${GENERATED_HEADER}\n${JSON.stringify(file.content, null, 2)}\n`
}

function renderSingle(input: DefineTsconfigInput): RenderedFile {
  const profile = input.profile
  const compilerOptions = mergeCompilerOptions(profile?.compilerOptions, input.compilerOptions)
  const content: RenderedTsconfig = {
    compilerOptions: normalizeCompilerOptions(compilerOptions),
    include: input.include ?? profile?.include,
    exclude: input.exclude ?? profile?.exclude,
    references: input.references,
  }
  pruneUndefined(content)
  return { filename: 'tsconfig.json', content }
}

function resolveLayer(
  name: string,
  input: DefineTsconfigInput,
  layers: Record<string, LayerInput>,
): RenderedTsconfig {
  const layer = layers[name]!
  const chain = buildLayerChain(name, layers)

  let compilerOptions = input.profile?.compilerOptions ?? {}
  compilerOptions = mergeCompilerOptions(compilerOptions, input.compilerOptions)
  for (const stepName of chain) {
    compilerOptions = mergeCompilerOptions(compilerOptions, layers[stepName]!.compilerOptions)
  }

  const content: RenderedTsconfig = {
    compilerOptions: normalizeCompilerOptions(compilerOptions),
    include: pickInclude(input, chain, layers),
    exclude: pickExclude(input, chain, layers),
    files: layer.files,
  }
  pruneUndefined(content)
  return content
}

function pruneUndefined(obj: object): void {
  // Unsafe cast is intentional: RenderedTsconfig doesn't carry an index
  // signature, but we only touch our own known optional fields here.
  // eslint-disable-next-line typescript-eslint/no-unsafe-type-assertion
  const record = obj as Record<string, unknown>
  for (const key of Object.keys(record)) {
    if (record[key] === undefined) delete record[key]
  }
}
