import { mergeCompilerOptions, normalizeCompilerOptions } from './merge'
import { validateCompilerOptions } from './validate'

import type {
  CompilerOptions,
  RenderInput,
  ViewInput,
  RenderedConfig,
  RenderedFile,
  RenderedTsconfig,
} from './types'

const GENERATED_HEADER = '// AUTO-GENERATED by @infra-x/tsconfig — do not edit directly.\n// Run `tsconfig` to regenerate.'

export function renderConfig(input: RenderInput): RenderedConfig {
  warnOptions(input.compilerOptions, 'compilerOptions')

  if (!input.views || input.views.length === 0) {
    return { files: [renderPrimary(input)] }
  }

  const files: RenderedFile[] = [renderPrimary(input)]
  for (const view of input.views) {
    warnOptions(view.compilerOptions, `view.${view.name}.compilerOptions`)
    files.push(renderView(view, input))
  }
  return { files }
}

export function fileToString(file: RenderedFile): string {
  return `${GENERATED_HEADER}\n${JSON.stringify(file.content, null, 2)}\n`
}

function renderPrimary(input: RenderInput): RenderedFile {
  const compilerOptions = normalizeCompilerOptions(
    mergeCompilerOptions(input.compilerOptions, undefined),
  )
  const content: RenderedTsconfig = {
    compilerOptions,
    include: input.include,
    exclude: input.exclude,
    references: input.references,
  }
  pruneUndefined(content)
  return { filename: 'tsconfig.json', content }
}

function renderView(view: ViewInput, input: RenderInput): RenderedFile {
  const compilerOptions = normalizeCompilerOptions(
    mergeCompilerOptions(input.compilerOptions, view.compilerOptions ?? {}),
  )
  const content: RenderedTsconfig = {
    compilerOptions,
    include: view.include ?? input.include,
    exclude: view.exclude ?? input.exclude,
  }
  pruneUndefined(content)
  return { filename: `tsconfig.${view.name}.json`, content }
}

function warnOptions(opts: CompilerOptions | undefined, context: string): void {
  if (!opts) return
  const warnings = validateCompilerOptions(opts as Record<string, unknown>)
  for (const w of warnings) {
    const hint = w.suggestion ? ` Did you mean "${w.suggestion}"?` : ''
    console.warn(`[tsconfig] ${context}: ${w.message}${hint}`)
  }
}

function pruneUndefined(obj: object): void {
  // eslint-disable-next-line typescript-eslint/no-unsafe-type-assertion
  const record = obj as Record<string, unknown>
  for (const key of Object.keys(record)) {
    if (record[key] === undefined) delete record[key]
  }
}
