import { mergeCompilerOptions, normalizeCompilerOptions } from './merge'
import { validateCompilerOptions } from './validate'

import type {
  CompilerOptions,
  RenderInput,
  RenderedConfig,
  RenderedFile,
  RenderedTsconfig,
} from './types'

export const GENERATED_HEADER =
  '// AUTO-GENERATED by @infra-x/tsconfig — do not edit directly.\n// Run `tsconfig` to regenerate.'

export function renderConfig(input: RenderInput): RenderedConfig {
  warnOptions(input.compilerOptions, 'compilerOptions')

  const files: RenderedFile[] = [
    renderFile('tsconfig.json', input.compilerOptions, {
      include: input.include,
      exclude: input.exclude,
      references: input.references,
    }),
  ]

  for (const view of input.views ?? []) {
    warnOptions(view.compilerOptions, `view.${view.name}.compilerOptions`)
    files.push(
      renderFile(
        `tsconfig.${view.name}.json`,
        mergeCompilerOptions(input.compilerOptions, view.compilerOptions ?? {}),
        { include: view.include ?? input.include, exclude: view.exclude ?? input.exclude },
      ),
    )
  }

  return { files }
}

export function fileToString(file: RenderedFile): string {
  return `${GENERATED_HEADER}\n${JSON.stringify(file.content, null, 2)}\n`
}

function renderFile(
  filename: string,
  compilerOptions: CompilerOptions,
  extra: Partial<Omit<RenderedTsconfig, 'compilerOptions'>>,
): RenderedFile {
  const content: RenderedTsconfig = {
    compilerOptions: normalizeCompilerOptions(compilerOptions),
    ...(extra.include !== undefined && { include: extra.include }),
    ...(extra.exclude !== undefined && { exclude: extra.exclude }),
    ...(extra.references !== undefined && { references: extra.references }),
    ...(extra.files !== undefined && { files: extra.files }),
  }
  return { filename, content }
}

function warnOptions(opts: CompilerOptions | undefined, context: string): void {
  if (!opts) return
  const warnings = validateCompilerOptions(opts as Record<string, unknown>)
  for (const w of warnings) {
    const hint = w.suggestion ? ` Did you mean "${w.suggestion}"?` : ''
    console.warn(`[tsconfig] ${context}: ${w.message}${hint}`)
  }
}
